meta_product_name: "Budbee"
meta_title: "Budbee-For students who wants to find friends and study groups"
meta_description: "We bring likeminded students together - to discuss, to learn, and to connect
"
meta_image: "favicon.ico" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
